# Generated by Django 2.2.14 on 2020-07-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloguser',
            options={'managed': True},
        ),
    ]
