# Generated by Django 2.2.14 on 2020-07-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_auto_20200711_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='user_name',
        ),
    ]
